name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker build -t my-python-app .
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag my-python-app ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app

      - name: Deploy to Docker Hub
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app
