name: Create GitHub Release

on:
  workflow_run:
    workflows: ["Build and Deploy Docker Container"]
    types:
      - completed

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          
      - name: Get Latest Tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --abbrev=0 --tags)
          echo "::set-output name=tag::$latest_tag"
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          tag_name: ${{ steps.latest_tag.outputs.tag }}
          release_name: Release ${{ steps.latest_tag.outputs.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          
      - name: Push Tag to GitHub
        run: git push origin ${{ steps.latest_tag.outputs.tag }}
