name: Create GitHub Release

on:
  workflow_run:
    workflows: ["Build and Deploy Docker Container"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"

      - name: Create GitHub Release
        run: |
          git tag -a v1.0.0 -m "Release v1.0.0"
          git push origin v1.0.0
